In [1]:
import numpy as np

In [2]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
type(data) 

numpy.ndarray

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim 

2

In [6]:
data.shape 

(3, 2)

In [7]:
data.size 

6

In [8]:
data.dtype 

dtype('int32')

In [9]:
data.nbytes

24

In [10]:
 np.array([1, 2, 3], dtype=np.int) 

array([1, 2, 3])

In [11]:
 np.array([1, 2, 3], dtype=np.float) 

array([1., 2., 3.])

In [12]:
np.array([1, 2, 3], dtype=np.complex) 

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
data = np.array([1, 2, 3], dtype=np.float) 

In [14]:
data

array([1., 2., 3.])

In [15]:
data.dtype

dtype('float64')

In [16]:
data = np.array(data, dtype=np.int) 

In [17]:
data.dtype 

dtype('int32')

In [18]:
data

array([1, 2, 3])

In [19]:
 data = np.array([1, 2, 3], dtype=np.float) 

In [20]:
data

array([1., 2., 3.])

In [21]:
data.astype(np.int) 

array([1, 2, 3])

In [22]:
d1 = np.array([1, 2, 3], dtype=float) 

In [23]:
d2 = np.array([1, 2, 3], dtype=complex) 

In [24]:
d1 + d2 

array([2.+0.j, 4.+0.j, 6.+0.j])

In [25]:
(d1 + d2).dtype 

dtype('complex128')

In [26]:
 np.sqrt(np.array([-1, 0, 1])) 

C:\Users\Sharon\Anaconda3\envs\tests\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [27]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

In [28]:
data = np.array([1, 2, 3], dtype=complex) 

In [29]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [30]:
data.real

array([1., 2., 3.])

In [31]:
data.imag

array([0., 0., 0.])

In [32]:
 np.array([1, 2, 3, 4]) 

array([1, 2, 3, 4])

In [33]:
data.ndim 

1

In [34]:
data.shape 

(3,)

In [35]:
np.array([[1, 2], [3, 4]]) 

array([[1, 2],
       [3, 4]])

In [36]:
data.ndim

1

In [37]:
data.shape

(3,)

In [38]:
np.zeros((2, 3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.ones(4) 

array([1., 1., 1., 1.])

In [40]:
 data = np.ones(4) 

In [41]:
data.dtype

dtype('float64')

In [42]:
data = np.ones(4, dtype=np.int64) 

In [43]:
data.dtype

dtype('int64')

In [44]:
x1 = 5.4 * np.ones(10) 

In [45]:
x2 = np.full(10, 5.4)

In [46]:
x1 = np.empty(5) 

In [47]:
x1.fill(3.0)

In [48]:
x1

array([3., 3., 3., 3., 3.])

In [49]:
x2 = np.full(5, 3.0)

In [50]:
x2

array([3., 3., 3., 3., 3.])

In [51]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [53]:
np.logspace(0, 2, 5)  # 5 data points between 10**0=1 to 10**2=100 

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [54]:
x = np.array([-1, 0, 1])

In [55]:
y = np.array([-2, 0, 2])

In [56]:
X, Y = np.meshgrid(x, y) 

In [57]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [58]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [59]:
 Z = (X + Y) ** 2 

In [60]:
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]], dtype=int32)

In [61]:
np.empty(3, dtype=np.float) 

array([0., 0., 0.])

In [62]:
np.identity(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
np.eye(3, k=1) 

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [64]:
np.eye(3, k=-1) 

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [65]:
np.diag(np.arange(0, 20, 5)) 

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [66]:
a = np.arange(0, 11) 

In [67]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
a[0] 

0

In [69]:
a[-1]

10

In [70]:
a[4]

4

In [71]:
 a[1:-1] 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a[1:-1:2] 

array([1, 3, 5, 7, 9])

In [73]:
a[:5] 

array([0, 1, 2, 3, 4])

In [74]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [75]:
 a[::-2] 

array([10,  8,  6,  4,  2,  0])

In [76]:
f = lambda m, n: n + 10 * m 

In [77]:
A = np.fromfunction(f, (6, 6), dtype=int) 

In [78]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [79]:
A[:, 1]

array([ 1, 11, 21, 31, 41, 51])

In [80]:
A[1, :]

array([10, 11, 12, 13, 14, 15])

In [81]:
A[:3, :3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [82]:
A[3:, :3]

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [83]:
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [84]:
A[1::2, 1::3]

array([[11, 14],
       [31, 34],
       [51, 54]])

In [85]:
 B = A[1:5, 1:5] 

In [86]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [87]:
B[:, :] = 0 

In [88]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [89]:
C = B[1:3, 1:3].copy() 

In [90]:
C

array([[0, 0],
       [0, 0]])

In [91]:
C[:, :] = 1 

In [92]:
C

array([[1, 1],
       [1, 1]])

In [93]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [94]:
A = np.linspace(0, 1, 11) 

In [95]:
A[np.array([0, 2, 4])] 

array([0. , 0.2, 0.4])

In [96]:
A[[0, 2, 4]]

array([0. , 0.2, 0.4])

In [97]:
A > 0.5 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [98]:
A[A > 0.5] 

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [99]:
A = np.arange(10) 

In [101]:
indices = [2, 4, 6] 

In [102]:
B = A[indices] 

In [103]:
B[0] = -1

In [104]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
A[indices] = -1

In [106]:
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [107]:
A = np.arange(10)

In [109]:
B = A[A > 5] 

In [110]:
B[0] = -1 

In [111]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
A[A > 5] = -1 

In [113]:
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

In [114]:
data = np.array([[1, 2], [3, 4]]) 

In [115]:
np.reshape(data, (1, 4)) 

array([[1, 2, 3, 4]])

In [116]:
data.reshape(4) 

array([1, 2, 3, 4])

In [117]:
data = np.array([[1, 2], [3, 4]]) 

In [118]:
data

array([[1, 2],
       [3, 4]])

In [119]:
data.flatten() 

array([1, 2, 3, 4])

In [120]:
data.flatten().shape

(4,)

In [121]:
data = np.arange(0, 5) 

In [122]:
column = data[:, np.newaxis] 

In [123]:
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [124]:
row = data[np.newaxis, :] 

In [125]:
row

array([[0, 1, 2, 3, 4]])

In [147]:
data = np.arange(5) 

In [148]:
data

array([0, 1, 2, 3, 4])

In [149]:
np.vstack((data, data, data)) 

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [126]:
data = np.arange(5) 

In [127]:
data

array([0, 1, 2, 3, 4])

In [128]:
np.hstack((data, data, data)) 

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [129]:
data = data[:, np.newaxis] 

In [130]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [131]:
x = np.array([[1, 2], [3, 4]]) 

In [132]:
y = np.array([[5, 6], [7, 8]]) 

In [133]:
x + y

array([[ 6,  8],
       [10, 12]])

In [134]:
y - x 

array([[4, 4],
       [4, 4]])

In [135]:
x * y 

array([[ 5, 12],
       [21, 32]])

In [136]:
y / x 

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [137]:
x * 2 

array([[2, 4],
       [6, 8]])

In [138]:
2 ** x 

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [139]:
y / 2 

array([[2.5, 3. ],
       [3.5, 4. ]])

In [143]:
(y / 2).dtype 

dtype('float64')

In [141]:
x = np.array([1, 2, 3, 4]).reshape(2, 2) 

In [142]:
z = np.array([1, 2, 3, 4]) 

In [144]:
x / z

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [145]:
z = np.array([[2, 4]]) 

In [146]:
z.shape 

(1, 2)

In [150]:
 x / z 

array([[0.5, 0.5],
       [1.5, 1. ]])

In [151]:
zz = np.concatenate([z, z], axis=0) 

In [152]:
zz

array([[2, 4],
       [2, 4]])

In [153]:
 x / zz 

array([[0.5, 0.5],
       [1.5, 1. ]])

In [154]:
z = np.array([[2], [4]])

In [155]:
z.shape

(2, 1)

In [156]:
x / z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [161]:
 zz = np.concatenate([z, z], axis=1) 

In [162]:
zz

array([[2, 2],
       [4, 4]])

In [163]:
x / zz 

ValueError: operands could not be broadcast together with shapes (11,) (2,2) 

In [157]:
x = x + y 

In [158]:
x += y

In [159]:
x = np.linspace(-1, 1, 11) 

In [160]:
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [164]:
y = np.sin(np.pi * x) 

In [165]:
np.round(y, decimals=4) 

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [166]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2) 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [167]:
np.sin(x) ** 2 + np.cos(x) ** 2 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [168]:
def heaviside(x):
        return 1 if x > 0 else 0 

In [169]:
heaviside(-1) 

0

In [170]:
heaviside(1.5) 

1

In [171]:
x = np.linspace(-5, 5, 11) 

In [172]:
heaviside(x) 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [173]:
heaviside = np.vectorize(heaviside)

In [174]:
heaviside(x) 

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [175]:
def heaviside(x):
    return 1.0 * (x > 0)

In [176]:
data = np.random.normal(size=(15,15)) 

In [177]:
np.mean(data)

0.05605364597821384

In [178]:
data.mean() 

0.05605364597821384

In [179]:
data = np.random.normal(size=(5, 10, 15)) 

In [180]:
data.sum(axis=0).shape 

(10, 15)

In [181]:
data.sum(axis=(0, 2)).shape 

(10,)

In [182]:
data.sum()

-34.64536197228685

In [183]:
data = np.arange(1,10).reshape(3,3) 

In [184]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [185]:
data.sum() 

45

In [186]:
data.sum(axis=0) 

array([12, 15, 18])

In [187]:
data.sum(axis=1) 

array([ 6, 15, 24])

In [188]:
a = np.array([1, 2, 3, 4]) 

In [189]:
b = np.array([4, 3, 2, 1]) 

In [190]:
a < b 

array([ True,  True, False, False])

In [191]:
np.all(a < b) 

False

In [192]:
np.any(a < b) 

True

In [196]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding element in b")
elif np.any(a < b):
    print("Some elements in a are smaller than their corresponding element in b")
else:
    print("All elements in b are smaller than their corresponding element in a")

Some elements in a are smaller than their corresponding element in b


In [197]:
x = np.array([-2, -1, 0, 1, 2]) 

In [198]:
x > 0 

array([False, False, False,  True,  True])

In [199]:
1 * (x > 0) 

array([0, 0, 0, 1, 1])

In [200]:
x * (x > 0) 

array([0, 0, 0, 1, 2])

In [201]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width)) 

In [202]:
x = np.linspace(-5, 5, 11) 

In [203]:
pulse(x, position=-2, height=1, width=5) 

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [204]:
pulse(x, position=1, height=1, width=5)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [205]:
def pulse(x, position, height, width):
    return height * np.logical_and(x >= position, x <= (position + width))

In [206]:
x = np.linspace(-4, 4, 9) 

In [207]:
np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [208]:
np.select([x < -1, x < 2, x >= 2],
          [x**2  , x**3 , x**4]) 

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [209]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2],
          [x**2,  x**3,  x**4]) 

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [210]:
np.nonzero(abs(x) > 2) 

(array([0, 1, 7, 8], dtype=int64),)

In [211]:
x[np.nonzero(abs(x) > 2)] 

array([-4., -3.,  3.,  4.])

In [212]:
x[abs(x) > 2] 

array([-4., -3.,  3.,  4.])

In [213]:
a = np.unique([1, 2, 3, 3]) 

In [214]:
b = np.unique([2, 3, 4, 4, 5, 6, 5]) 

In [215]:
np.in1d(a, b) 

array([False,  True,  True])

In [216]:
1 in a 

True

In [217]:
1 in b

False

In [218]:
np.all(np.in1d(a, b)) 

False

In [219]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [220]:
np.intersect1d(a, b) 

array([2, 3])

In [221]:
np.setdiff1d(a, b) 

array([1])

In [222]:
np.setdiff1d(b, a) 

array([4, 5, 6])

In [223]:
data = np.arange(9).reshape(3, 3) 

In [224]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [225]:
np.transpose(data) 

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [226]:
data = np.random.randn(1, 2, 3, 4, 5) 

In [227]:
data.shape

(1, 2, 3, 4, 5)

In [228]:
data.T.shape 

(5, 4, 3, 2, 1)

In [229]:
A = np.arange(1, 7).reshape(2, 3)

In [230]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [231]:
B = np.arange(1, 7).reshape(3, 2) 

In [232]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [233]:
np.dot(A, B) 

array([[22, 28],
       [49, 64]])

In [234]:
np.dot(B, A) 

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [235]:
A = np.arange(9).reshape(3, 3) 

In [236]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [237]:
x = np.arange(3)

In [238]:
x

array([0, 1, 2])

In [239]:
np.dot(A, x) 

array([ 5, 14, 23])

In [240]:
A.dot(x) 

array([ 5, 14, 23])

In [241]:
A = np.random.rand(3,3) 

In [242]:
B = np.random.rand(3,3) 

In [243]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))

In [244]:
Ap = B.dot(A.dot(np.linalg.inv(B)))

In [245]:
A = np.matrix(A) 

In [246]:
B = np.matrix(B) 

In [247]:
Ap = B * A * B.I

In [248]:
A = np.asmatrix(A) 

In [249]:
B = np.asmatrix(B) 

In [250]:
Ap = B * A * B.I 

In [251]:
Ap = np.asarray(Ap)

In [252]:
np.inner(x, x) 

5

In [253]:
np.dot(x, x) 

5

In [254]:
y = x[:, np.newaxis] 

In [255]:
y

array([[0],
       [1],
       [2]])

In [256]:
np.dot(y.T, y) 

array([[5]])

In [257]:
x = np.array([1, 2, 3]) 

In [258]:
np.outer(x, x) 

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [259]:
np.kron(x, x)

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [260]:
np.kron(x[:, np.newaxis], x[np.newaxis, :]) 

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [261]:
np.kron(np.ones((2,2)), np.identity(2)) 

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [262]:
np.kron(np.identity(2), np.ones((2,2))) 

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [263]:
x = np.array([1, 2, 3, 4])

In [264]:
y = np.array([5, 6, 7, 8]) 

In [265]:
np.einsum("n,n", x, y) 

70

In [266]:
np.inner(x, y) 

70

In [267]:
A = np.arange(9).reshape(3, 3) 

In [268]:
B = A.T 

In [269]:
np.einsum("mk,kn", A, B) 

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [270]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B)) 

True